/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
public object Libs {
    public const val appcompat: String = "androidx.appcompat:appcompat:_"

    public const val core_testing: String = "androidx.arch.core:core-testing:_"

    public const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:_"

    public const val core_ktx: String = "androidx.core:core-ktx:_"

    public const val databinding_adapters: String = "androidx.databinding:databinding-adapters:_"

    public const val databinding_common: String = "androidx.databinding:databinding-common:_"

    public const val databinding_compiler: String = "androidx.databinding:databinding-compiler:_"

    public const val databinding_ktx: String = "androidx.databinding:databinding-ktx:_"

    public const val databinding_runtime: String = "androidx.databinding:databinding-runtime:_"

    public const val viewbinding: String = "androidx.databinding:viewbinding:_"

    public const val fragment_ktx: String = "androidx.fragment:fragment-ktx:_"

    public const val androidx_hilt_hilt_compiler: String = "androidx.hilt:hilt-compiler:_"

    public const val hilt_work: String = "androidx.hilt:hilt-work:_"

    public const val lifecycle_livedata_ktx: String = "androidx.lifecycle:lifecycle-livedata-ktx:_"

    public const val lifecycle_runtime_ktx: String = "androidx.lifecycle:lifecycle-runtime-ktx:_"

    public const val lifecycle_viewmodel_ktx: String =
            "androidx.lifecycle:lifecycle-viewmodel-ktx:_"

    public const val lifecycle_viewmodel_savedstate: String =
            "androidx.lifecycle:lifecycle-viewmodel-savedstate:_"

    public const val navigation_fragment_ktx: String =
            "androidx.navigation:navigation-fragment-ktx:_"

    public const val navigation_safe_args_gradle_plugin: String =
            "androidx.navigation:navigation-safe-args-gradle-plugin:_"

    public const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:_"

    public const val recyclerview: String = "androidx.recyclerview:recyclerview:_"

    public const val room_compiler: String = "androidx.room:room-compiler:_"

    public const val room_ktx: String = "androidx.room:room-ktx:_"

    public const val room_runtime: String = "androidx.room:room-runtime:_"

    public const val swiperefreshlayout: String = "androidx.swiperefreshlayout:swiperefreshlayout:_"

    public const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    public const val androidx_test_ext_junit: String = "androidx.test.ext:junit:_"

    public const val work_runtime_ktx: String = "androidx.work:work-runtime-ktx:_"

    public const val turbine: String = "app.cash.turbine:turbine:_"

    public const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    public const val lint_gradle: String = "com.android.tools.lint:lint-gradle:_"

    public const val material: String = "com.google.android.material:material:_"

    public const val hilt_android: String = "com.google.dagger:hilt-android:_"

    public const val hilt_android_gradle_plugin: String =
            "com.google.dagger:hilt-android-gradle-plugin:_"

    public const val com_google_dagger_hilt_compiler: String = "com.google.dagger:hilt-compiler:_"

    public const val truth: String = "com.google.truth:truth:_"

    public const val retrofit2_kotlin_coroutines_adapter: String =
            "com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:_"

    public const val moshi_kotlin: String = "com.squareup.moshi:moshi-kotlin:_"

    public const val moshi_kotlin_codegen: String = "com.squareup.moshi:moshi-kotlin-codegen:_"

    public const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:_"

    public const val converter_moshi: String = "com.squareup.retrofit2:converter-moshi:_"

    public const val retrofit: String = "com.squareup.retrofit2:retrofit:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val coil: String = "io.coil-kt:coil:_"

    public const val mockk: String = "io.mockk:mockk:_"

    public const val mockk_android: String = "io.mockk:mockk-android:_"

    public const val junit_junit: String = "junit:junit:_"

    public const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:_"

    public const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:_"

    public const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"

    public const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:_"

    public const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:_"

    public const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:_"

    public const val kotlinx_coroutines_test: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-test:_"
}
